README.md
=> starter readme info

client/src/components/Login.jsx, client/src/components/Logout.jsx, client/src/components/Register.jsx, package-lock.json, package.json
In this I have include an npm install for Auth0 for our react and vite for this is stage. I have also added code to the login and logout.jsx
=>  added auth npm and files to the login and logout

client/package-lock.json, client/package.json, client/postcss.config.js, client/src/App.jsx, client/src/components/Register.jsx, client/src/index.css, client/tailwind.config.js, package-lock.json, package.json
=> add register form

server/schemas/index.js, server/schemas/resolvers.js, server/schemas/typeDefs.js
I have included the templates for our schema resolvers based on course material that can be acclimated to our project for what we need.
=>  added boiler plate for the schema index/resolvers/typeDefs

client/README.md, client/src/components/Login.jsx, client/src/index.jsx
basic basic login form , to get things working
=> basic login starter

client/package-lock.json, client/package.json, client/src/App.jsx, client/src/components/Lesson.jsx, client/src/components/Lessons/Lesson.jsx, client/src/components/Lessons/Lesson2.jsx, client/src/lessons.js
i added 2 lessons, one for alex to start working on the backend with and another multiple choice proof of concept one
=> add one lesson

client/src/components/Dashboard.jsx, client/src/components/Footer.jsx, client/src/components/Header.jsx, package-lock.json, package.json
basic layouts , not final 
dashboard is confusing me , taking a break lol ....
=> basic layouts

client/src/components/Dashboard.jsx, client/src/components/Home.jsx
slowly working on dashboard 
updated home page
=> Dashboard+Home

server/utils/seeds/answerData.json, server/utils/seeds/lessonData.json, server/utils/seeds/problemData.json
Lesson, problem and answer json data added and organized to function with seeding logic.
=> Feat seeds

client/package-lock.json, client/package.json, client/src/components/Home.jsx, client/src/components/ParticleEffect.jsx, package-lock.json, package.json
effects for fun , only on homepage can add it to other pages 
or change the shape ext , place holder
=> playing with effect options

client/src/components/Donation.jsx, client/src/components/Profile.jsx, package-lock.json, package.json, server/server.js
i changed the root dir's package.json scripts a bit, in prep for production
=> Feat donate

client/src/App.jsx, client/src/components/Login.jsx, client/src/components/Logout.jsx, client/src/components/Register.jsx, client/src/index.jsx, client/utils/auth.js, client/utils/mutations.js, client/utils/queries.js
I have added some of the vanilla code to get this login moving
=>  added logic and modified our login ro work with new auth

client/src/components/Css.jsx, client/src/components/Html.jsx, client/src/components/JavaScript.jsx, server/package-lock.json
=> starter lesson pages

client/src/components/Css.jsx, client/src/components/Html.jsx, client/src/components/JavaScript.jsx
=> Lessonpages

client/.eslintrc.cjs, client/package-lock.json, client/package.json, client/vite.config.js, package-lock.json, package.json, server/package-lock.json, server/package.json, server/server.js
I made changes to the package.JSON in both the client and server side as well as the route package.
=> maded changes primarily to the package.json and config files

client/src/components/Login.jsx, client/src/components/LoginButton.jsx, client/vite.config.js, server/server.js
=> made changes to the login page

client/src/components/Login.jsx, client/src/components/Register.jsx, client/utils/mutations.js
=>  added changes to the register

client/src/components/Dashboard.jsx, client/src/components/Footer.jsx, client/src/components/Home.jsx, client/src/components/Html.jsx, client/src/components/JavaScript.jsx, client/src/reset.css
globally forced background 100vh full screen and forced footer to the bottom
=> fixed background and footer errors

client/src/components/Footer.jsx, client/src/components/Login.jsx, client/src/components/Register.jsx
Cosmetic changes removing from black boxes
=> cosmetics for login and register

client/src/components/Html.jsx
=> working on connecting answers

client/src/components/Header.jsx, client/src/components/Login.jsx, client/src/components/Logout.jsx, client/src/components/LogoutButton.jsx, client/src/components/Profile.jsx, client/vite.config.js
just fixed some of the auth imports
=> Feat check auth

client/src/components/Dashboard.jsx, client/src/reset.css
last pr for now dashboard pretty much finished , few minor adjustments
=> last pr for the night

client/src/components/Dashboard.jsx
=> fixed class name errors
